# orchestration/config/constants.py
"""
Global constants for the Mind Protocol orchestration.
Named numbers, thresholds, capacities, tick/sleep intervals, backoff, etc.
"""

# Energy
ENERGY_THRESHOLD_ACTIVE = 0.75

# Timeouts and intervals
DEFAULT_TIMEOUT_SEC = 30.0
DEFAULT_BACKOFF_SECONDS = 0.1
TICK_INTERVAL_MS_MIN = 50
TICK_INTERVAL_MS_MAX = 1000

# Retries
DEFAULT_RETRIES = 3

# Capacities
WORKING_MEMORY_CAPACITY = 9

# Engine
ENGINE_TICK_INTERVAL_MS = 10000.0

# Criticality
CRITICALITY_CONTROLLER_KP = 0.05
CRITICALITY_CONTROLLER_SAMPLE_RHO_EVERY_N_FRAMES = 5
CRITICALITY_DEFAULT_DECAY_RATE = 0.03
CRITICALITY_DEFAULT_DIFFUSION_RATE = 0.1

# Branching Ratio
BRANCHING_RATIO_TRACKER_WINDOW_SIZE = 10

# Broadcaster
SAFE_BROADCASTER_MAX_SPILL_SIZE = 1000

# Telemetry
TELEMETRY_BUS_FPS = 10

# Learning
WEIGHT_LEARNER_ALPHA = 0.1
WEIGHT_LEARNER_MIN_COHORT_SIZE = 3

# Sub-entity
SUBENTITY_COHORT_TRACKER_WINDOW_SIZE = 100
SUBENTITY_CONTEXT_TRACKER_ALPHA_AFFECT = 0.1
SUBENTITY_CONTEXT_TRACKER_ALPHA_CONTEXT = 0.05

# Persistence
PERSIST_MIN_BATCH = 25
PERSIST_INTERVAL_SEC = 5.0
PERSIST_JITTER = 0.5

# Flip
FLIP_FPS = 10
FLIP_TOPK = 25

# Stimulus
DEFAULT_STIMULUS_SEVERITY = 0.3
DEFAULT_VECTOR_SIMILARITY = 0.5
KEYWORD_RELEVANCE_SCALE = 0.3
SEED_SIMILARITY = 0.15
SEED_LIMIT = 50

# Gap Analysis
GAP_ANALYSIS_TOP_K = 20

# Strides
STRIDE_EXECUTION_SAMPLE_RATE = 0.1
ATOMIC_STRIDE_EXECUTION_SAMPLE_RATE = 0.3

# Tripwire
TRIPWIRE_CONSERVATION_EPSILON = 0.001

# Decay
WEIGHT_DECAY_INTERVAL_TICKS = 60
HISTOGRAM_COMPUTATION_INTERVAL_TICKS = 100

# Health
PHENOMENOLOGY_HEALTH_INTERVAL_TICKS = 5

# Merge
SUBENTITY_MERGE_SCAN_INTERVAL_TICKS = 50
MERGE_CANDIDATES_Q90_THRESHOLD = 0.7

# Flip
NODE_FLIP_TOP_K = 20

# Link Flow
LINK_FLOW_SUMMARY_SAMPLE_RATE = 0.10

# Phenomenology
PHENOMENOLOGY_MISMATCH_THRESHOLD = 0.3

# Working Memory
WM_DRIFT_THRESHOLD = 0.1
WM_COACTIVATION_ALPHA = 0.1
TOKEN_ESTIMATE_CHARS_PER_TOKEN = 4
WORKSPACE_TOKEN_BUDGET = 2000
ENTITY_SUMMARY_TOKEN_COST = 50
ENTITY_MEMBER_TOKEN_COST = 10
DIVERSITY_BONUS_SCALE = 0.5
MAX_WORKSPACE_ENTITIES = 7

# Dirty Node
DIRTY_NODE_DEADBAND = 0.5

# Embedding
EMBEDDING_TIMEOUT_S = 2.0
EMBEDDING_CIRCUIT_BREAKER_COOLDOWN_S = 30.0
