"""
Find correct Phantom wallet derivation

Tries multiple common derivation paths to find which matches your address
"""

from solders.keypair import Keypair
from mnemonic import Mnemonic
import getpass

TARGET_ADDRESS = "HXctV9Ue8KUKoLHXmvqutKj93ATToHKxWShMnZc3ydxn"

print("🔍 Finding Your Phantom Wallet")
print("="*70)
print(f"\nTarget address: {TARGET_ADDRESS}")
print("\n⚠️  Input will be hidden for security\n")

# Get recovery phrase
recovery_phrase = getpass.getpass("Recovery phrase (12 or 24 words): ").strip()

words = recovery_phrase.split()
if len(words) not in [12, 24]:
    print(f"\n❌ Invalid: Expected 12 or 24 words, got {len(words)}")
    exit(1)

print(f"\n✅ Received {len(words)}-word phrase")

# Validate
mnemo = Mnemonic("english")
if not mnemo.check(recovery_phrase):
    print("\n❌ Invalid recovery phrase")
    exit(1)

print("✅ Recovery phrase valid\n")
print("🔍 Trying different derivation methods...\n")

# Generate seed
seed = mnemo.to_seed(recovery_phrase)

# Method 1: Direct seed (first 32 bytes)
print("Method 1: Direct seed derivation")
try:
    keypair1 = Keypair.from_seed(seed[:32])
    print(f"   Address: {keypair1.pubkey()}")
    if str(keypair1.pubkey()) == TARGET_ADDRESS:
        print("   ✅ MATCH FOUND!")
        keypair = keypair1
        method = "direct_seed"
except Exception as e:
    print(f"   ❌ Failed: {e}")

# Method 2: Try with passphrase (empty passphrase is default)
print("\nMethod 2: Seed with empty passphrase")
try:
    seed2 = mnemo.to_seed(recovery_phrase, passphrase="")
    keypair2 = Keypair.from_seed(seed2[:32])
    print(f"   Address: {keypair2.pubkey()}")
    if str(keypair2.pubkey()) == TARGET_ADDRESS:
        print("   ✅ MATCH FOUND!")
        keypair = keypair2
        method = "empty_passphrase"
except Exception as e:
    print(f"   ❌ Failed: {e}")

# Method 3: Try account indices 0-10 (if Phantom has multiple accounts)
print("\nMethod 3: Multiple account indices")
for i in range(10):
    try:
        # Try offset by account index
        account_seed = seed[i:i+32] if i+32 <= len(seed) else seed[:32]
        keypair_i = Keypair.from_seed(account_seed)

        if str(keypair_i.pubkey()) == TARGET_ADDRESS:
            print(f"   ✅ MATCH FOUND at index {i}!")
            print(f"   Address: {keypair_i.pubkey()}")
            keypair = keypair_i
            method = f"account_index_{i}"
            break
        elif i < 3:  # Only show first 3 to avoid spam
            print(f"   Account {i}: {keypair_i.pubkey()}")
    except:
        pass

# Check if we found a match
try:
    if 'keypair' in locals() and str(keypair.pubkey()) == TARGET_ADDRESS:
        print("\n" + "="*70)
        print("✅ WALLET FOUND!")
        print("="*70)
        print(f"\nMatching address: {keypair.pubkey()}")
        print(f"Method: {method}")

        # Save keypair
        import json
        output_file = "phantom_keypair_matched.json"
        with open(output_file, 'w') as f:
            json.dump(list(bytes(keypair)), f)

        print(f"\n✅ Keypair saved to: {output_file}")
        print(f"\n🔐 Next step:")
        print(f"   python orchestration/economy/secure_key_manager.py import deployer_mainnet {output_file}")
        print(f"\n⚠️  Then delete temp files!")
    else:
        print("\n" + "="*70)
        print("❌ NO MATCH FOUND")
        print("="*70)
        print("\nPossible issues:")
        print("  1. Wrong recovery phrase (check Phantom again)")
        print("  2. Phantom using custom derivation path")
        print("  3. Imported wallet (not generated by Phantom)")
        print("\nAlternative: Export private key directly from Phantom")
        print("   Settings → Security & Privacy → Export Private Key")
except Exception as e:
    print(f"\n❌ Error: {e}")
